version: '3.9'

networks:
  product-network:
    driver: bridge
    name: product-network

services:
  database-product-postgres:
    container_name: product-db
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - PGUSER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_HOST_PORT:$POSTGRES_CONTAINER_PORT
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - product-network
    healthcheck:
      test:  [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 100
  
  productapi:
    container_name: product-api
    environment:
      - POSTGRES_DSN=$POSTGRES_DSN
      - API_PORT=$API_CONTAINER_PORT
    build:
      context: .
      dockerfile: Dockerfile.api-golang
    ports:
      - $API_HOST_PORT:$API_CONTAINER_PORT
    networks:
      - product-network
    depends_on:
      database-product-postgres:
        condition: service_healthy